Update(Rules): Apple, Global

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -71,7 +71,7 @@ jobs:
             # 合并 GFW 规则
             urls=(
                 "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"
-                "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/gfw.txt"
+                "https://ruleset.skk.moe/List/non_ip/global.conf"
             )
             > Tool-repo/Ruleset/ProxyGFW.list
             for url in "${urls[@]}"; do
@@ -94,14 +94,25 @@ jobs:
             # 合并 AppleProxy 规则
             urls=(
                 "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AppleProxy/AppleProxy.list"
-                "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AppStore/AppStore.list"
+                "https://raw.githubusercontent.com/Repcz/Tool/refs/heads/X/Surge/Custom/AppStoreDownload.list"
             )
             > Tool-repo/Ruleset/AppleProxy.list
             for url in "${urls[@]}"; do
                 echo "Downloading: $url"
                 curl -f -L -H "Accept-Language: en-us" "$url" >> Tool-repo/Ruleset/AppleProxy.list || { echo "Download Failed: $url"; exit 1; }
                 echo "" >> Tool-repo/Ruleset/AppleProxy.list
-            done            
+            done
+            # 合并 AppleCN 规则
+            urls=(
+                "https://ruleset.skk.moe/List/non_ip/apple_cn.conf"
+                "https://ruleset.skk.moe/List/non_ip/apple_cdn.conf"
+            )
+            > Tool-repo/Ruleset/AppleCN.list
+            for url in "${urls[@]}"; do
+                echo "Downloading: $url"
+                curl -f -L -H "Accept-Language: en-us" "$url" >> Tool-repo/Ruleset/AppleProxy.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/AppleCN.list
+            done
             # 下载规则
             files=(
                 # 苹果
@@ -112,6 +123,7 @@ jobs:
                 "AppleID.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/AppleID/AppleID.list"
                 "iCloud.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/iCloud/iCloud.list"
                 "TestFlight.list https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/TestFlight/TestFlight.list"
+                "AppleServers.list https://ruleset.skk.moe/List/non_ip/apple_services.conf"
                 # AI
                 "OpenAI.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list"
                 "Claude.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Claude.list"
