Fix(wrokflows): AI, AppleProxy

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -85,11 +85,11 @@ jobs:
                 "https://raw.githubusercontent.com/Repcz/Tool/X/Surge/Custom/xAI.list"
                 "https://raw.githubusercontent.com/Repcz/Tool/X/Surge/Custom/AI.list"
             )
-            > Tool-repo/Ruleset/AppleProxy.list
+            > Tool-repo/Ruleset/AI.list
             for url in "${urls[@]}"; do
                 echo "Downloading: $url"
-                curl -f -L "$url" >> Tool-repo/Ruleset/AppleProxy.list || { echo "Download Failed: $url"; exit 1; }
-                echo "" >> Tool-repo/Ruleset/AppleProxy.list
+                curl -f -L "$url" >> Tool-repo/Ruleset/AI.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/AI.list
             done
             # 合并 AppleProxy 规则
             urls=(
@@ -99,9 +99,10 @@ jobs:
             > Tool-repo/Ruleset/AI.list
             for url in "${urls[@]}"; do
                 echo "Downloading: $url"
-                curl -f -L "$url" >> Tool-repo/Ruleset/AI.list || { echo "Download Failed: $url"; exit 1; }
-                echo "" >> Tool-repo/Ruleset/AI.list
-            done            # 下载规则
+                curl -f -L "$url" >> Tool-repo/Ruleset/AppleProxy.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/AppleProxy.list
+            done            
+            # 下载规则
             files=(
                 # 苹果
                 "APNs.list https://kelee.one/Tool/Loon/Rule/ApplePushNotificationService.list"
